### PR TITLE
added flake8 check in travis

### PR DESCRIPTION
**Pull request by mirkobronzi**

### CODE REVIEW

**Comment by mirkobronzi** [comment]
> If flake8 is put as something that can break the travis build if it doesn't pass, we may want to configure it to remove certain types of errors (for instance line length >79).
> Another option is to run flake8 outside of travis (something like this for instance). Doing it outside of travis will give us both the flake8 and the test outputs even if flake8 fails.

right - both are interesting. For the first, I have no problem in blocking too long line.
80 is ok to me, but we may want to move to 100 if you prefer.

For the second, I really like the idea to have both run no matter what - I'll try to play with it..

**Comment by carriepl** [comment]
You can look at https://github.com/OrkoHunter/pep8speaks

**Comment by mirkobronzi** [comment]
so, it seems to work to me: both unittest and flake8 are run no matter what - and both are blocking (which is what we want)

**Comment by carriepl** [comment]
Ok, great!

**Pull request merged**
